server:
 servlet:
    context-path: /pessoa-endereco/api
    
spring:
  data:
    mongodb:
      authentication-database: admin
      uri: ${MONGO_DB_URI:mongodb+srv://attornatus:140665@attornatus.lfykhvp.mongodb.net/Attornatus?retryWrites=true&w=majority}
      auto-index-creation: true 

springdoc:
  swagger-ui:
    path: /public/swagger
 